# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyringeConfigurationController.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sila2lib.framework.SiLAFramework_pb2 as SiLAFramework__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SyringeConfigurationController.proto',
  package='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$SyringeConfigurationController.proto\x12\x44sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1\x1a\x13SiLAFramework.proto\"\x8d\x01\n\x1fSetSyringeParameters_Parameters\x12\x33\n\rInnerDiameter\x18\x01 \x01(\x0b\x32\x1c.sila2.org.silastandard.Real\x12\x35\n\x0fMaxPistonStroke\x18\x02 \x01(\x0b\x32\x1c.sila2.org.silastandard.Real\" \n\x1eSetSyringeParameters_Responses\"$\n\"Subscribe_InnerDiameter_Parameters\"X\n!Subscribe_InnerDiameter_Responses\x12\x33\n\rInnerDiameter\x18\x01 \x01(\x0b\x32\x1c.sila2.org.silastandard.Real\"&\n$Subscribe_MaxPistonStroke_Parameters\"\\\n#Subscribe_MaxPistonStroke_Responses\x12\x35\n\x0fMaxPistonStroke\x18\x01 \x01(\x0b\x32\x1c.sila2.org.silastandard.Real2\xf4\x05\n\x1eSyringeConfigurationController\x12\xe5\x01\n\x14SetSyringeParameters\x12\x65.sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Parameters\x1a\x64.sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Responses\"\x00\x12\xf0\x01\n\x17Subscribe_InnerDiameter\x12h.sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_InnerDiameter_Parameters\x1ag.sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_InnerDiameter_Responses\"\x00\x30\x01\x12\xf6\x01\n\x19Subscribe_MaxPistonStroke\x12j.sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_MaxPistonStroke_Parameters\x1ai.sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_MaxPistonStroke_Responses\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[SiLAFramework__pb2.DESCRIPTOR,])




_SETSYRINGEPARAMETERS_PARAMETERS = _descriptor.Descriptor(
  name='SetSyringeParameters_Parameters',
  full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='InnerDiameter', full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Parameters.InnerDiameter', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxPistonStroke', full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Parameters.MaxPistonStroke', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=273,
)


_SETSYRINGEPARAMETERS_RESPONSES = _descriptor.Descriptor(
  name='SetSyringeParameters_Responses',
  full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=307,
)


_SUBSCRIBE_INNERDIAMETER_PARAMETERS = _descriptor.Descriptor(
  name='Subscribe_InnerDiameter_Parameters',
  full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_InnerDiameter_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=345,
)


_SUBSCRIBE_INNERDIAMETER_RESPONSES = _descriptor.Descriptor(
  name='Subscribe_InnerDiameter_Responses',
  full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_InnerDiameter_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='InnerDiameter', full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_InnerDiameter_Responses.InnerDiameter', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=435,
)


_SUBSCRIBE_MAXPISTONSTROKE_PARAMETERS = _descriptor.Descriptor(
  name='Subscribe_MaxPistonStroke_Parameters',
  full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_MaxPistonStroke_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=475,
)


_SUBSCRIBE_MAXPISTONSTROKE_RESPONSES = _descriptor.Descriptor(
  name='Subscribe_MaxPistonStroke_Responses',
  full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_MaxPistonStroke_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MaxPistonStroke', full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_MaxPistonStroke_Responses.MaxPistonStroke', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=569,
)

_SETSYRINGEPARAMETERS_PARAMETERS.fields_by_name['InnerDiameter'].message_type = SiLAFramework__pb2._REAL
_SETSYRINGEPARAMETERS_PARAMETERS.fields_by_name['MaxPistonStroke'].message_type = SiLAFramework__pb2._REAL
_SUBSCRIBE_INNERDIAMETER_RESPONSES.fields_by_name['InnerDiameter'].message_type = SiLAFramework__pb2._REAL
_SUBSCRIBE_MAXPISTONSTROKE_RESPONSES.fields_by_name['MaxPistonStroke'].message_type = SiLAFramework__pb2._REAL
DESCRIPTOR.message_types_by_name['SetSyringeParameters_Parameters'] = _SETSYRINGEPARAMETERS_PARAMETERS
DESCRIPTOR.message_types_by_name['SetSyringeParameters_Responses'] = _SETSYRINGEPARAMETERS_RESPONSES
DESCRIPTOR.message_types_by_name['Subscribe_InnerDiameter_Parameters'] = _SUBSCRIBE_INNERDIAMETER_PARAMETERS
DESCRIPTOR.message_types_by_name['Subscribe_InnerDiameter_Responses'] = _SUBSCRIBE_INNERDIAMETER_RESPONSES
DESCRIPTOR.message_types_by_name['Subscribe_MaxPistonStroke_Parameters'] = _SUBSCRIBE_MAXPISTONSTROKE_PARAMETERS
DESCRIPTOR.message_types_by_name['Subscribe_MaxPistonStroke_Responses'] = _SUBSCRIBE_MAXPISTONSTROKE_RESPONSES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetSyringeParameters_Parameters = _reflection.GeneratedProtocolMessageType('SetSyringeParameters_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _SETSYRINGEPARAMETERS_PARAMETERS,
  '__module__' : 'SyringeConfigurationController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Parameters)
  })
_sym_db.RegisterMessage(SetSyringeParameters_Parameters)

SetSyringeParameters_Responses = _reflection.GeneratedProtocolMessageType('SetSyringeParameters_Responses', (_message.Message,), {
  'DESCRIPTOR' : _SETSYRINGEPARAMETERS_RESPONSES,
  '__module__' : 'SyringeConfigurationController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SetSyringeParameters_Responses)
  })
_sym_db.RegisterMessage(SetSyringeParameters_Responses)

Subscribe_InnerDiameter_Parameters = _reflection.GeneratedProtocolMessageType('Subscribe_InnerDiameter_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_INNERDIAMETER_PARAMETERS,
  '__module__' : 'SyringeConfigurationController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_InnerDiameter_Parameters)
  })
_sym_db.RegisterMessage(Subscribe_InnerDiameter_Parameters)

Subscribe_InnerDiameter_Responses = _reflection.GeneratedProtocolMessageType('Subscribe_InnerDiameter_Responses', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_INNERDIAMETER_RESPONSES,
  '__module__' : 'SyringeConfigurationController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_InnerDiameter_Responses)
  })
_sym_db.RegisterMessage(Subscribe_InnerDiameter_Responses)

Subscribe_MaxPistonStroke_Parameters = _reflection.GeneratedProtocolMessageType('Subscribe_MaxPistonStroke_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_MAXPISTONSTROKE_PARAMETERS,
  '__module__' : 'SyringeConfigurationController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_MaxPistonStroke_Parameters)
  })
_sym_db.RegisterMessage(Subscribe_MaxPistonStroke_Parameters)

Subscribe_MaxPistonStroke_Responses = _reflection.GeneratedProtocolMessageType('Subscribe_MaxPistonStroke_Responses', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_MAXPISTONSTROKE_RESPONSES,
  '__module__' : 'SyringeConfigurationController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.Subscribe_MaxPistonStroke_Responses)
  })
_sym_db.RegisterMessage(Subscribe_MaxPistonStroke_Responses)



_SYRINGECONFIGURATIONCONTROLLER = _descriptor.ServiceDescriptor(
  name='SyringeConfigurationController',
  full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SyringeConfigurationController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=572,
  serialized_end=1328,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetSyringeParameters',
    full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SyringeConfigurationController.SetSyringeParameters',
    index=0,
    containing_service=None,
    input_type=_SETSYRINGEPARAMETERS_PARAMETERS,
    output_type=_SETSYRINGEPARAMETERS_RESPONSES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe_InnerDiameter',
    full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SyringeConfigurationController.Subscribe_InnerDiameter',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBE_INNERDIAMETER_PARAMETERS,
    output_type=_SUBSCRIBE_INNERDIAMETER_RESPONSES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe_MaxPistonStroke',
    full_name='sila2.de.cetoni.pumps.syringepumps.syringeconfigurationcontroller.v1.SyringeConfigurationController.Subscribe_MaxPistonStroke',
    index=2,
    containing_service=None,
    input_type=_SUBSCRIBE_MAXPISTONSTROKE_PARAMETERS,
    output_type=_SUBSCRIBE_MAXPISTONSTROKE_RESPONSES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYRINGECONFIGURATIONCONTROLLER)

DESCRIPTOR.services_by_name['SyringeConfigurationController'] = _SYRINGECONFIGURATIONCONTROLLER

# @@protoc_insertion_point(module_scope)
