#!/usr/bin/env python3
"""
________________________________________________________________________

:PROJECT: SiLA2_python

*Contiflow*

:details: Contiflow:
    Allows to control a continuous flow pumps that is made up of two syringe pumps
           
:file:    Contiflow_server.py
:authors: Florian Meinicke

:date: (creation)          2020-10-22T07:15:55.315248
:date: (last modification) 2020-10-22T07:15:55.315248

.. note:: Code generated by sila2codegenerator 0.3.2.dev

________________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""
__version__ = "0.1.0"

import logging
import argparse

# Import the main SiLA library
from sila2lib.sila_server import SiLA2Server

# Import gRPC libraries of features
from de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService.gRPC import de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_pb2
from de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService.gRPC import de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_pb2_grpc
# import default arguments for this feature
from de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService.de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_default_arguments import default_dict as de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_default_dict
from de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController.gRPC import de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_pb2
from de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController.gRPC import de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_pb2_grpc
# import default arguments for this feature
from de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController.de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_default_arguments import default_dict as de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_default_dict

# Import the servicer modules for each feature
from de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService.de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_servicer import de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService
from de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController.de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_servicer import de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController


class ContiflowServer(SiLA2Server):
    """
    Allows to control a continuous flow pumps that is made up of two syringe pumps
    """

    def __init__(self, cmd_args, simulation_mode: bool = True):
        """Class initialiser"""
        super().__init__(
            name=cmd_args.server_name, description=cmd_args.description,
            server_type=cmd_args.server_type, server_uuid=None,
            version=__version__,
            vendor_url="cetoni.de",
            ip="127.0.0.1", port=50053,
            key_file=cmd_args.encryption_key, cert_file=cmd_args.encryption_cert
        )

        logging.info(
            "Starting SiLA2 server with server name: {server_name}".format(
                server_name=cmd_args.server_name
            )
        )

        # registering features
        #  Register de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService
        self.de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_servicer = de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService(simulation_mode=self.simulation_mode)
        de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_pb2_grpc.add_de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationServiceServicer_to_server(
            self.de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_servicer,
            self.grpc_server
        )
        self.add_feature(feature_id='de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService',
                         servicer=self.de/cetoni/pumps/contiflowpumps/ContinuousFlowConfigurationService_servicer,
                         data_path='meta')
        #  Register de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController
        self.de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_servicer = de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController(simulation_mode=self.simulation_mode)
        de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_pb2_grpc.add_de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationControllerServicer_to_server(
            self.de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_servicer,
            self.grpc_server
        )
        self.add_feature(feature_id='de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController',
                         servicer=self.de/cetoni/pumps/contiflowpumps/ContinuousFlowInitializationController_servicer,
                         data_path='meta')

        self.simulation_mode = simulation_mode

        # starting and running the gRPC/SiLA2 server
        self.run()


def parse_command_line():
    """
    Just looking for commandline arguments
    """
    parser = argparse.ArgumentParser(description="A SiLA2 service: Contiflow")

    # Simple arguments for the server identification
    parser.add_argument('-s', '--server-name', action='store',
                        default="Contiflow", help='start SiLA server with [server-name]')
    parser.add_argument('-t', '--server-type', action='store',
                        default="Unknown Type", help='start SiLA server with [server-type]')
    parser.add_argument('-d', '--description', action='store',
                        default="Allows to control a continuous flow pumps that is made up of two syringe pumps", help='SiLA server description')

    # Encryption
    parser.add_argument('-X', '--encryption', action='store', default=None,
                        help='The name of the private key and certificate file (without extension).')
    parser.add_argument('--encryption-key', action='store', default=None,
                        help='The name of the encryption key (*with* extension). Can be used if key and certificate '
                             'vary or non-standard file extensions are used.')
    parser.add_argument('--encryption-cert', action='store', default=None,
                        help='The name of the encryption certificate (*with* extension). Can be used if key and '
                             'certificate vary or non-standard file extensions are used.')

    parser.add_argument('-v', '--version', action='version', version='%(prog)s ' + __version__)

    parsed_args = parser.parse_args()

    # validate/update some settings
    #   encryption
    if parsed_args.encryption is not None:
        # only overwrite the separate keys if not given manually
        if parsed_args.encryption_key is None:
            parsed_args.encryption_key = parsed_args.encryption + '.key'
        if parsed_args.encryption_cert is None:
            parsed_args.encryption_cert = parsed_args.encryption + '.cert'

    return parsed_args
    
        
if __name__ == '__main__':
    # or use logging.ERROR for less output
    logging.basicConfig(format='%(levelname)-8s| %(module)s.%(funcName)s: %(message)s', level=logging.DEBUG)
    
    args = parse_command_line()

    # generate SiLA2Server
    sila_server = ContiflowServer(cmd_args=args, simulation_mode=True)
